kind: pipeline
type: docker
name: demo
steps:
  - name: deploy_nginx
    image: appleboy/drone-ssh:linux-amd64
    volumes:
      - name: ssh_key
        path: /root/ssh/drone_rsa
    settings:
        host:
            from_secret: host
        username:
            from_secret: username
        key_path: /root/ssh/drone_rsa
        script:
          - echo ========== Deploy Nginx with Docker ==========
          - docker pull nginx
          - docker run -d -p 3000:80 nginx
          - docker ps
volumes:
  - name: ssh_key
    host:
        path: /home/noti/.ssh/noti