version: "3.7"
services:
  drone-server:
    image: drone/drone:2
    container_name: local_drone_server
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/lib/drone:/var/lib/drone
    env_file:
      - ./.env
    
  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: local_drone_runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - drone-server
    env_file:
      - ./.env
    
volumes:
  drone: